###
GET http://localhost:3001/api/notes

###
POST http://localhost:3001/notes
Content-Type: application/json

{
    "content": "hello api",
    "important": false
}
###

POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content":"trying out something",
    "important": false
}